//! FFI bindings to FlashInfer C++/CUDA kernels.
//!
//! This module provides safe Rust wrappers over the C API defined in
//! `csrc/flashinfer_c_api.h`. The bindings are generated by bindgen
//! during the build process.
//!
//! # Building
//!
//! To build with CUDA support:
//! ```bash
//! cargo build --features cuda
//! ```
//!
//! Requirements:
//! - CUDA toolkit (set `CUDA_HOME` or `CUDA_PATH`)
//! - FlashInfer source (in `references/flashinfer/` or set `FLASHINFER_PATH`)
//! - C++17 compiler
//!
//! # Example
//!
//! ```ignore
//! use flashinfer_rs::ffi::{BatchDecodePlan, DType, KVLayout};
//!
//! let plan = BatchDecodePlan::new(config)?;
//! plan.run(&query, &kv_cache, &page_table, &mut output)?;
//! ```

// Include the generated bindings
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
#[allow(clippy::all)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/ffi_generated.rs"));
}

pub use generated::*;

use crate::{FlashInferError, Result};
use std::ffi::CStr;
use std::ptr;

/// Convert FFI status to Result
fn check_status(status: FlashInferStatus) -> Result<()> {
    match status {
        FlashInferStatus::FLASHINFER_SUCCESS => Ok(()),
        FlashInferStatus::FLASHINFER_CUDA_ERROR => {
            let msg = get_last_error().unwrap_or_else(|| "Unknown CUDA error".to_string());
            Err(FlashInferError::cuda(msg))
        }
        FlashInferStatus::FLASHINFER_INVALID_ARGUMENT => {
            let msg = get_last_error().unwrap_or_else(|| "Invalid argument".to_string());
            Err(FlashInferError::invalid_config(msg))
        }
        FlashInferStatus::FLASHINFER_OUT_OF_MEMORY => {
            let msg = get_last_error().unwrap_or_else(|| "Out of memory".to_string());
            Err(FlashInferError::OutOfMemory(msg))
        }
        FlashInferStatus::FLASHINFER_UNSUPPORTED => {
            let msg = get_last_error().unwrap_or_else(|| "Unsupported operation".to_string());
            Err(FlashInferError::unsupported(msg))
        }
        FlashInferStatus::FLASHINFER_INTERNAL_ERROR => {
            let msg = get_last_error().unwrap_or_else(|| "Internal error".to_string());
            Err(FlashInferError::Internal(msg))
        }
        FlashInferStatus::FLASHINFER_NOT_INITIALIZED => {
            let msg = get_last_error().unwrap_or_else(|| "Not initialized".to_string());
            Err(FlashInferError::Internal(msg))
        }
    }
}

/// Get the last error message from the FFI layer.
pub fn get_last_error() -> Option<String> {
    unsafe {
        let ptr = flashinfer_get_last_error();
        if ptr.is_null() {
            None
        } else {
            Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
        }
    }
}

/// Clear the last error message.
pub fn clear_last_error() {
    unsafe {
        flashinfer_clear_last_error();
    }
}

/// Get FlashInfer version string.
pub fn version() -> &'static str {
    unsafe {
        let ptr = flashinfer_version();
        if ptr.is_null() {
            "unknown"
        } else {
            CStr::from_ptr(ptr).to_str().unwrap_or("unknown")
        }
    }
}

/// Check if the current GPU supports FlashInfer operations.
///
/// Returns (supported, sm_version) where sm_version is e.g. 80 for SM80.
pub fn check_gpu_support() -> Result<(bool, i32)> {
    let mut supported: i32 = 0;
    let mut sm_version: i32 = 0;

    let status = unsafe { flashinfer_check_gpu_support(&mut supported, &mut sm_version) };

    check_status(status)?;
    Ok((supported != 0, sm_version))
}

/// Data type for attention computation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DType {
    Float16,
    BFloat16,
    Float32,
    Float8E4M3,
    Float8E5M2,
}

impl From<DType> for FlashInferDType {
    fn from(dtype: DType) -> Self {
        match dtype {
            DType::Float16 => FlashInferDType::FLASHINFER_DTYPE_FLOAT16,
            DType::BFloat16 => FlashInferDType::FLASHINFER_DTYPE_BFLOAT16,
            DType::Float32 => FlashInferDType::FLASHINFER_DTYPE_FLOAT32,
            DType::Float8E4M3 => FlashInferDType::FLASHINFER_DTYPE_FLOAT8_E4M3,
            DType::Float8E5M2 => FlashInferDType::FLASHINFER_DTYPE_FLOAT8_E5M2,
        }
    }
}

impl From<crate::types::DType> for DType {
    fn from(dtype: crate::types::DType) -> Self {
        match dtype {
            crate::types::DType::Float16 => DType::Float16,
            crate::types::DType::BFloat16 => DType::BFloat16,
            crate::types::DType::Float32 => DType::Float32,
            crate::types::DType::Float8E4M3 => DType::Float8E4M3,
            crate::types::DType::Float8E5M2 => DType::Float8E5M2,
        }
    }
}

/// KV cache memory layout.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KVLayout {
    /// [num_pages, num_heads, page_size, head_dim]
    HND,
    /// [num_pages, page_size, num_heads, head_dim]
    NHD,
}

impl From<KVLayout> for FlashInferKVLayout {
    fn from(layout: KVLayout) -> Self {
        match layout {
            KVLayout::HND => FlashInferKVLayout::FLASHINFER_KV_LAYOUT_HND,
            KVLayout::NHD => FlashInferKVLayout::FLASHINFER_KV_LAYOUT_NHD,
        }
    }
}

impl From<crate::types::KVLayout> for KVLayout {
    fn from(layout: crate::types::KVLayout) -> Self {
        match layout {
            crate::types::KVLayout::HND => KVLayout::HND,
            crate::types::KVLayout::NHD => KVLayout::NHD,
        }
    }
}

/// Position encoding mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum PosEncoding {
    #[default]
    None,
    RoPELlama,
    ALiBi,
    RoPELlamaFreqScale,
}

impl From<PosEncoding> for FlashInferPosEncoding {
    fn from(enc: PosEncoding) -> Self {
        match enc {
            PosEncoding::None => FlashInferPosEncoding::FLASHINFER_POS_ENCODING_NONE,
            PosEncoding::RoPELlama => FlashInferPosEncoding::FLASHINFER_POS_ENCODING_ROPE_LLAMA,
            PosEncoding::ALiBi => FlashInferPosEncoding::FLASHINFER_POS_ENCODING_ALIBI,
            PosEncoding::RoPELlamaFreqScale => FlashInferPosEncoding::FLASHINFER_POS_ENCODING_ROPE_LLAMA_FREQ_SCALE,
        }
    }
}

impl From<crate::types::PosEncodingMode> for PosEncoding {
    fn from(mode: crate::types::PosEncodingMode) -> Self {
        match mode {
            crate::types::PosEncodingMode::None => PosEncoding::None,
            crate::types::PosEncodingMode::RoPELlama => PosEncoding::RoPELlama,
            crate::types::PosEncodingMode::ALiBi => PosEncoding::ALiBi,
            crate::types::PosEncodingMode::RoPELlamaFreqScale => PosEncoding::RoPELlamaFreqScale,
        }
    }
}

/// Attention mask mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum MaskMode {
    #[default]
    None,
    Causal,
    Custom,
}

impl From<MaskMode> for FlashInferMaskMode {
    fn from(mode: MaskMode) -> Self {
        match mode {
            MaskMode::None => FlashInferMaskMode_FLASHINFER_MASK_NONE,
            MaskMode::Causal => FlashInferMaskMode_FLASHINFER_MASK_CAUSAL,
            MaskMode::Custom => FlashInferMaskMode_FLASHINFER_MASK_CUSTOM,
        }
    }
}

impl From<crate::types::MaskMode> for MaskMode {
    fn from(mode: crate::types::MaskMode) -> Self {
        match mode {
            crate::types::MaskMode::None => MaskMode::None,
            crate::types::MaskMode::Causal => MaskMode::Causal,
            crate::types::MaskMode::Custom => MaskMode::Custom,
        }
    }
}

/// Attention backend selection.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Backend {
    #[default]
    Auto,
    FA2,
    FA3,
    CuDNN,
}

impl From<Backend> for FlashInferBackend {
    fn from(backend: Backend) -> Self {
        match backend {
            Backend::Auto => FlashInferBackend_FLASHINFER_BACKEND_AUTO,
            Backend::FA2 => FlashInferBackend_FLASHINFER_BACKEND_FA2,
            Backend::FA3 => FlashInferBackend_FLASHINFER_BACKEND_FA3,
            Backend::CuDNN => FlashInferBackend_FLASHINFER_BACKEND_CUDNN,
        }
    }
}

impl From<crate::types::Backend> for Backend {
    fn from(backend: crate::types::Backend) -> Self {
        match backend {
            crate::types::Backend::Auto => Backend::Auto,
            crate::types::Backend::FA2 => Backend::FA2,
            crate::types::Backend::FA3 => Backend::FA3,
            crate::types::Backend::CuDNN => Backend::CuDNN,
        }
    }
}

/// Get required workspace sizes for batch decode operation.
pub fn batch_decode_workspace_size(
    batch_size: i32,
    num_qo_heads: i32,
    num_kv_heads: i32,
    head_dim: i32,
    page_size: i32,
    max_seq_len: i32,
) -> Result<(usize, usize)> {
    let mut float_size: usize = 0;
    let mut int_size: usize = 0;

    let status = unsafe {
        flashinfer_batch_decode_workspace_size(
            &mut float_size,
            &mut int_size,
            batch_size,
            num_qo_heads,
            num_kv_heads,
            head_dim,
            page_size,
            max_seq_len,
        )
    };

    check_status(status)?;
    Ok((float_size, int_size))
}

/// Get required workspace sizes for batch prefill operation.
pub fn batch_prefill_workspace_size(
    batch_size: i32,
    total_tokens: i32,
    num_qo_heads: i32,
    num_kv_heads: i32,
    head_dim: i32,
    page_size: i32,
    max_seq_len: i32,
) -> Result<(usize, usize)> {
    let mut float_size: usize = 0;
    let mut int_size: usize = 0;

    let status = unsafe {
        flashinfer_batch_prefill_workspace_size(
            &mut float_size,
            &mut int_size,
            batch_size,
            total_tokens,
            num_qo_heads,
            num_kv_heads,
            head_dim,
            page_size,
            max_seq_len,
        )
    };

    check_status(status)?;
    Ok((float_size, int_size))
}

/// RAII wrapper for batch decode plan.
pub struct BatchDecodePlan {
    handle: FlashInferBatchDecodePlanHandle,
}

impl BatchDecodePlan {
    /// Create a new batch decode plan.
    ///
    /// # Arguments
    /// * `float_workspace` - GPU buffer for float workspace
    /// * `int_workspace` - GPU buffer for int workspace
    /// * `page_locked_workspace` - Page-locked host memory (optional, can be null)
    /// * `kv_indptr` - Cumulative page counts [batch_size + 1]
    /// * `batch_size` - Number of sequences
    /// * `num_qo_heads` - Number of query/output heads
    /// * `num_kv_heads` - Number of key/value heads
    /// * `head_dim` - Head dimension
    /// * `page_size` - Tokens per page
    /// * `dtype` - Data type
    /// * `pos_encoding` - Position encoding mode
    /// * `logits_soft_cap` - Soft cap for logits (0 to disable)
    /// * `window_left` - Sliding window size (-1 for full attention)
    /// * `enable_cuda_graph` - Whether this will run in a CUDA graph
    /// * `stream` - CUDA stream (raw pointer)
    #[allow(clippy::too_many_arguments)]
    pub unsafe fn new(
        float_workspace: *mut std::ffi::c_void,
        float_workspace_size: usize,
        int_workspace: *mut std::ffi::c_void,
        int_workspace_size: usize,
        page_locked_workspace: *mut std::ffi::c_void,
        page_locked_size: usize,
        kv_indptr: *const i32,
        batch_size: i32,
        num_qo_heads: i32,
        num_kv_heads: i32,
        head_dim: i32,
        page_size: i32,
        dtype: DType,
        pos_encoding: PosEncoding,
        logits_soft_cap: f32,
        window_left: i32,
        enable_cuda_graph: bool,
        stream: *mut std::ffi::c_void,
    ) -> Result<Self> {
        let mut handle: FlashInferBatchDecodePlanHandle = ptr::null_mut();

        let status = flashinfer_batch_decode_plan(
            &mut handle,
            float_workspace,
            float_workspace_size,
            int_workspace,
            int_workspace_size,
            page_locked_workspace,
            page_locked_size,
            kv_indptr,
            batch_size,
            num_qo_heads,
            num_kv_heads,
            head_dim,
            page_size,
            dtype.into(),
            pos_encoding.into(),
            logits_soft_cap,
            window_left,
            enable_cuda_graph as i32,
            stream,
        );

        check_status(status)?;
        Ok(Self { handle })
    }

    /// Execute batch decode with this plan.
    #[allow(clippy::too_many_arguments)]
    pub unsafe fn run(
        &self,
        q: *const std::ffi::c_void,
        k_cache: *const std::ffi::c_void,
        v_cache: *const std::ffi::c_void,
        kv_indptr: *const i32,
        kv_indices: *const i32,
        kv_last_page_len: *const i32,
        output: *mut std::ffi::c_void,
        lse: *mut f32,
        kv_layout: KVLayout,
        stream: *mut std::ffi::c_void,
    ) -> Result<()> {
        let status = flashinfer_batch_decode_run(
            self.handle,
            q,
            k_cache,
            v_cache,
            kv_indptr,
            kv_indices,
            kv_last_page_len,
            output,
            lse,
            kv_layout.into(),
            stream,
        );

        check_status(status)
    }
}

impl Drop for BatchDecodePlan {
    fn drop(&mut self) {
        unsafe {
            flashinfer_batch_decode_plan_destroy(self.handle);
        }
    }
}

// BatchDecodePlan is Send but not Sync (single-threaded use)
unsafe impl Send for BatchDecodePlan {}

/// RAII wrapper for batch prefill plan.
pub struct BatchPrefillPlan {
    handle: FlashInferBatchPrefillPlanHandle,
}

impl BatchPrefillPlan {
    /// Create a new batch prefill plan.
    ///
    /// # Arguments
    /// * `window_left` - Sliding window size (-1 for full attention)
    #[allow(clippy::too_many_arguments)]
    pub unsafe fn new(
        float_workspace: *mut std::ffi::c_void,
        float_workspace_size: usize,
        int_workspace: *mut std::ffi::c_void,
        int_workspace_size: usize,
        page_locked_workspace: *mut std::ffi::c_void,
        page_locked_size: usize,
        qo_indptr: *const i32,
        kv_indptr: *const i32,
        batch_size: i32,
        num_qo_heads: i32,
        num_kv_heads: i32,
        head_dim: i32,
        page_size: i32,
        dtype: DType,
        pos_encoding: PosEncoding,
        logits_soft_cap: f32,
        window_left: i32,
        causal: bool,
        enable_cuda_graph: bool,
        stream: *mut std::ffi::c_void,
    ) -> Result<Self> {
        let mut handle: FlashInferBatchPrefillPlanHandle = ptr::null_mut();

        let status = flashinfer_batch_prefill_plan(
            &mut handle,
            float_workspace,
            float_workspace_size,
            int_workspace,
            int_workspace_size,
            page_locked_workspace,
            page_locked_size,
            qo_indptr,
            kv_indptr,
            batch_size,
            num_qo_heads,
            num_kv_heads,
            head_dim,
            page_size,
            dtype.into(),
            pos_encoding.into(),
            logits_soft_cap,
            window_left,
            causal as i32,
            enable_cuda_graph as i32,
            stream,
        );

        check_status(status)?;
        Ok(Self { handle })
    }

    /// Execute batch prefill with this plan.
    #[allow(clippy::too_many_arguments)]
    pub unsafe fn run(
        &self,
        q: *const std::ffi::c_void,
        k_cache: *const std::ffi::c_void,
        v_cache: *const std::ffi::c_void,
        kv_indptr: *const i32,
        kv_indices: *const i32,
        kv_last_page_len: *const i32,
        qo_indptr: *const i32,
        output: *mut std::ffi::c_void,
        lse: *mut f32,
        kv_layout: KVLayout,
        stream: *mut std::ffi::c_void,
    ) -> Result<()> {
        let status = flashinfer_batch_prefill_run(
            self.handle,
            q,
            k_cache,
            v_cache,
            kv_indptr,
            kv_indices,
            kv_last_page_len,
            qo_indptr,
            output,
            lse,
            kv_layout.into(),
            stream,
        );

        check_status(status)
    }
}

impl Drop for BatchPrefillPlan {
    fn drop(&mut self) {
        unsafe {
            flashinfer_batch_prefill_plan_destroy(self.handle);
        }
    }
}

unsafe impl Send for BatchPrefillPlan {}

/// Append new key-value pairs to paged KV cache.
#[allow(clippy::too_many_arguments)]
pub unsafe fn append_paged_kv_cache(
    k: *const std::ffi::c_void,
    v: *const std::ffi::c_void,
    k_cache: *mut std::ffi::c_void,
    v_cache: *mut std::ffi::c_void,
    kv_indptr: *const i32,
    kv_indices: *const i32,
    kv_last_page_len: *const i32,
    append_indptr: *const i32,
    batch_size: i32,
    num_kv_heads: i32,
    head_dim: i32,
    page_size: i32,
    dtype: DType,
    kv_layout: KVLayout,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_append_paged_kv_cache(
        k,
        v,
        k_cache,
        v_cache,
        kv_indptr,
        kv_indices,
        kv_last_page_len,
        append_indptr,
        batch_size,
        num_kv_heads,
        head_dim,
        page_size,
        dtype.into(),
        kv_layout.into(),
        stream,
    );

    check_status(status)
}

// =============================================================================
// RoPE API wrappers
// =============================================================================

/// Apply RoPE to Q and K tensors using batch indptr/offsets.
#[allow(clippy::too_many_arguments)]
pub unsafe fn apply_rope(
    q: *const std::ffi::c_void,
    k: *const std::ffi::c_void,
    q_out: *mut std::ffi::c_void,
    k_out: *mut std::ffi::c_void,
    indptr: *const i32,
    offsets: *const i32,
    batch_size: u32,
    num_qo_heads: u32,
    num_kv_heads: u32,
    head_dim: u32,
    config: &FlashInferRoPEConfig,
    dtype: DType,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_apply_rope(
        q,
        k,
        q_out,
        k_out,
        indptr,
        offsets,
        batch_size,
        num_qo_heads,
        num_kv_heads,
        head_dim,
        config as *const FlashInferRoPEConfig,
        dtype.into(),
        stream,
    );
    check_status(status)
}

/// Apply RoPE in-place to Q and K tensors.
#[allow(clippy::too_many_arguments)]
pub unsafe fn apply_rope_inplace(
    q: *mut std::ffi::c_void,
    k: *mut std::ffi::c_void,
    indptr: *const i32,
    offsets: *const i32,
    batch_size: u32,
    num_qo_heads: u32,
    num_kv_heads: u32,
    head_dim: u32,
    config: &FlashInferRoPEConfig,
    dtype: DType,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_apply_rope_inplace(
        q,
        k,
        indptr,
        offsets,
        batch_size,
        num_qo_heads,
        num_kv_heads,
        head_dim,
        config as *const FlashInferRoPEConfig,
        dtype.into(),
        stream,
    );
    check_status(status)
}

/// Apply RoPE with explicit position IDs.
#[allow(clippy::too_many_arguments)]
pub unsafe fn apply_rope_pos_ids(
    q: *const std::ffi::c_void,
    k: *const std::ffi::c_void,
    q_out: *mut std::ffi::c_void,
    k_out: *mut std::ffi::c_void,
    pos_ids: *const i32,
    total_tokens: u32,
    num_qo_heads: u32,
    num_kv_heads: u32,
    head_dim: u32,
    config: &FlashInferRoPEConfig,
    dtype: DType,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_apply_rope_pos_ids(
        q,
        k,
        q_out,
        k_out,
        pos_ids,
        total_tokens,
        num_qo_heads,
        num_kv_heads,
        head_dim,
        config as *const FlashInferRoPEConfig,
        dtype.into(),
        stream,
    );
    check_status(status)
}

/// Apply RoPE with precomputed cos/sin cache.
#[allow(clippy::too_many_arguments)]
pub unsafe fn apply_rope_with_cos_sin_cache(
    q: *const std::ffi::c_void,
    k: *const std::ffi::c_void,
    q_out: *mut std::ffi::c_void,
    k_out: *mut std::ffi::c_void,
    cos_sin_cache: *const std::ffi::c_void,
    pos_ids: *const i32,
    total_tokens: u32,
    num_qo_heads: u32,
    num_kv_heads: u32,
    head_dim: u32,
    config: &FlashInferRoPEConfig,
    dtype: DType,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_apply_rope_with_cos_sin_cache(
        q,
        k,
        q_out,
        k_out,
        cos_sin_cache,
        std::ptr::null(),  // sin_cache not used (combined in cos_sin_cache)
        pos_ids,
        total_tokens,
        num_qo_heads,
        num_kv_heads,
        head_dim,
        config as *const FlashInferRoPEConfig,
        dtype.into(),
        stream,
    );
    check_status(status)
}

// =============================================================================
// Sampling FFI Wrappers
// =============================================================================

/// Top-K sampling from probability distribution.
///
/// NOTE: Only supports float32 dtype due to type compatibility issues in FlashInfer's
/// internal arithmetic with half/bf16 types.
///
/// # Safety
/// All pointers must be valid and point to device memory.
#[allow(clippy::too_many_arguments)]
pub unsafe fn top_k_sampling(
    probs: *const f32,
    output: *mut i32,
    top_k_arr: *const i32, // NULL for uniform top_k_val
    top_k_val: u32,
    batch_size: u32,
    vocab_size: u32,
    deterministic: bool,
    philox_seed: u64,
    philox_offset: u64,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_top_k_sampling(
        probs as *const std::ffi::c_void,
        output,
        top_k_arr,
        top_k_val,
        batch_size,
        vocab_size,
        if deterministic { 1 } else { 0 },
        philox_seed,
        philox_offset,
        FlashInferDType::FLASHINFER_DTYPE_FLOAT32,
        stream,
    );
    check_status(status)
}

/// Top-P (nucleus) sampling from probability distribution.
///
/// NOTE: Only supports float32 dtype.
///
/// # Safety
/// All pointers must be valid and point to device memory.
#[allow(clippy::too_many_arguments)]
pub unsafe fn top_p_sampling(
    probs: *const f32,
    output: *mut i32,
    top_p_arr: *const f32, // NULL for uniform top_p_val
    top_p_val: f32,
    batch_size: u32,
    vocab_size: u32,
    deterministic: bool,
    philox_seed: u64,
    philox_offset: u64,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_top_p_sampling(
        probs as *const std::ffi::c_void,
        output,
        top_p_arr,
        top_p_val,
        batch_size,
        vocab_size,
        if deterministic { 1 } else { 0 },
        philox_seed,
        philox_offset,
        FlashInferDType::FLASHINFER_DTYPE_FLOAT32,
        stream,
    );
    check_status(status)
}

/// Min-P sampling from probability distribution.
///
/// NOTE: Only supports float32 dtype.
///
/// # Safety
/// All pointers must be valid and point to device memory.
#[allow(clippy::too_many_arguments)]
pub unsafe fn min_p_sampling(
    probs: *const f32,
    output: *mut i32,
    min_p_arr: *const f32, // NULL for uniform min_p_val
    min_p_val: f32,
    batch_size: u32,
    vocab_size: u32,
    deterministic: bool,
    philox_seed: u64,
    philox_offset: u64,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_min_p_sampling(
        probs as *const std::ffi::c_void,
        output,
        min_p_arr,
        min_p_val,
        batch_size,
        vocab_size,
        if deterministic { 1 } else { 0 },
        philox_seed,
        philox_offset,
        FlashInferDType::FLASHINFER_DTYPE_FLOAT32,
        stream,
    );
    check_status(status)
}

/// Combined Top-K + Top-P sampling.
///
/// NOTE: Only supports float32 dtype.
///
/// # Safety
/// All pointers must be valid and point to device memory.
#[allow(clippy::too_many_arguments)]
pub unsafe fn top_k_top_p_sampling(
    probs: *const f32,
    output: *mut i32,
    top_k_arr: *const i32, // NULL for uniform top_k_val
    top_p_arr: *const f32, // NULL for uniform top_p_val
    top_k_val: u32,
    top_p_val: f32,
    batch_size: u32,
    vocab_size: u32,
    deterministic: bool,
    philox_seed: u64,
    philox_offset: u64,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_top_k_top_p_sampling(
        probs as *const std::ffi::c_void,
        output,
        top_k_arr,
        top_p_arr,
        top_k_val,
        top_p_val,
        batch_size,
        vocab_size,
        if deterministic { 1 } else { 0 },
        philox_seed,
        philox_offset,
        FlashInferDType::FLASHINFER_DTYPE_FLOAT32,
        stream,
    );
    check_status(status)
}

/// Softmax with optional temperature scaling.
///
/// NOTE: Only supports float32 dtype.
///
/// # Safety
/// All pointers must be valid and point to device memory.
#[allow(clippy::too_many_arguments)]
pub unsafe fn softmax(
    logits: *const f32,
    probs: *mut f32,
    temperature_arr: *const f32, // NULL for uniform temp_val
    temp_val: f32,
    batch_size: u32,
    vocab_size: u32,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_softmax(
        logits as *const std::ffi::c_void,
        probs as *mut std::ffi::c_void,
        temperature_arr,
        temp_val,
        batch_size,
        vocab_size,
        FlashInferDType::FLASHINFER_DTYPE_FLOAT32,
        stream,
    );
    check_status(status)
}

/// Renormalize probabilities after top-p filtering.
///
/// NOTE: Only supports float32 dtype.
///
/// # Safety
/// All pointers must be valid and point to device memory.
#[allow(clippy::too_many_arguments)]
pub unsafe fn top_p_renorm_probs(
    probs: *const f32,
    renormed_probs: *mut f32,
    top_p_arr: *const f32, // NULL for uniform top_p_val
    top_p_val: f32,
    batch_size: u32,
    vocab_size: u32,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_top_p_renorm_probs(
        probs as *const std::ffi::c_void,
        renormed_probs as *mut std::ffi::c_void,
        top_p_arr,
        top_p_val,
        batch_size,
        vocab_size,
        FlashInferDType::FLASHINFER_DTYPE_FLOAT32,
        stream,
    );
    check_status(status)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version() {
        let v = version();
        assert!(!v.is_empty());
    }

    #[test]
    fn test_dtype_conversion() {
        assert_eq!(
            FlashInferDType::from(DType::Float16),
            FlashInferDType::FLASHINFER_DTYPE_FLOAT16
        );
        assert_eq!(
            FlashInferDType::from(DType::BFloat16),
            FlashInferDType::FLASHINFER_DTYPE_BFLOAT16
        );
        assert_eq!(
            FlashInferDType::from(DType::Float8E4M3),
            FlashInferDType::FLASHINFER_DTYPE_FLOAT8_E4M3
        );
    }

    #[test]
    fn test_layout_conversion() {
        assert_eq!(
            FlashInferKVLayout::from(KVLayout::HND),
            FlashInferKVLayout::FLASHINFER_KV_LAYOUT_HND
        );
        assert_eq!(
            FlashInferKVLayout::from(KVLayout::NHD),
            FlashInferKVLayout::FLASHINFER_KV_LAYOUT_NHD
        );
    }

    #[test]
    fn test_pos_encoding_conversion() {
        assert_eq!(
            FlashInferPosEncoding::from(PosEncoding::None),
            FlashInferPosEncoding::FLASHINFER_POS_ENCODING_NONE
        );
        assert_eq!(
            FlashInferPosEncoding::from(PosEncoding::RoPELlama),
            FlashInferPosEncoding::FLASHINFER_POS_ENCODING_ROPE_LLAMA
        );
        assert_eq!(
            FlashInferPosEncoding::from(PosEncoding::RoPELlamaFreqScale),
            FlashInferPosEncoding::FLASHINFER_POS_ENCODING_ROPE_LLAMA_FREQ_SCALE
        );
    }

    #[test]
    fn test_mask_mode_conversion() {
        assert_eq!(
            FlashInferMaskMode::from(MaskMode::None),
            FlashInferMaskMode_FLASHINFER_MASK_NONE
        );
        assert_eq!(
            FlashInferMaskMode::from(MaskMode::Causal),
            FlashInferMaskMode_FLASHINFER_MASK_CAUSAL
        );
        assert_eq!(
            FlashInferMaskMode::from(MaskMode::Custom),
            FlashInferMaskMode_FLASHINFER_MASK_CUSTOM
        );
    }

    #[test]
    fn test_backend_conversion() {
        assert_eq!(
            FlashInferBackend::from(Backend::Auto),
            FlashInferBackend_FLASHINFER_BACKEND_AUTO
        );
        assert_eq!(
            FlashInferBackend::from(Backend::FA2),
            FlashInferBackend_FLASHINFER_BACKEND_FA2
        );
        assert_eq!(
            FlashInferBackend::from(Backend::FA3),
            FlashInferBackend_FLASHINFER_BACKEND_FA3
        );
    }

    #[test]
    fn test_types_module_conversions() {
        // Test conversion from types module types to FFI types
        let dtype: DType = crate::types::DType::Float16.into();
        assert_eq!(dtype, DType::Float16);

        let layout: KVLayout = crate::types::KVLayout::NHD.into();
        assert_eq!(layout, KVLayout::NHD);

        let pos_enc: PosEncoding = crate::types::PosEncodingMode::RoPELlama.into();
        assert_eq!(pos_enc, PosEncoding::RoPELlama);

        let mask: MaskMode = crate::types::MaskMode::Causal.into();
        assert_eq!(mask, MaskMode::Causal);

        let backend: Backend = crate::types::Backend::FA2.into();
        assert_eq!(backend, Backend::FA2);
    }
}
