//! FFI bindings to FlashInfer C++/CUDA kernels.
//!
//! This module provides safe Rust wrappers over the C API defined in
//! `csrc/flashinfer_c_api.h`. The bindings are generated by bindgen
//! during the build process.
//!
//! # Building
//!
//! To build with CUDA support:
//! ```bash
//! cargo build --features cuda
//! ```
//!
//! Requirements:
//! - CUDA toolkit (set `CUDA_HOME` or `CUDA_PATH`)
//! - FlashInfer source (in `references/flashinfer/` or set `FLASHINFER_PATH`)
//! - C++17 compiler
//!
//! # Example
//!
//! ```ignore
//! use flashinfer_rs::ffi::{BatchDecodePlan, DType, KVLayout};
//!
//! let plan = BatchDecodePlan::new(config)?;
//! plan.run(&query, &kv_cache, &page_table, &mut output)?;
//! ```

// Include the generated bindings
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
#[allow(clippy::all)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/ffi_generated.rs"));
}

pub use generated::*;

use crate::{FlashInferError, Result};
use std::ffi::CStr;
use std::ptr;

/// Convert FFI status to Result
fn check_status(status: FlashInferStatus) -> Result<()> {
    match status {
        FlashInferStatus::FLASHINFER_SUCCESS => Ok(()),
        FlashInferStatus::FLASHINFER_CUDA_ERROR => {
            let msg = get_last_error().unwrap_or_else(|| "Unknown CUDA error".to_string());
            Err(FlashInferError::cuda(msg))
        }
        FlashInferStatus::FLASHINFER_INVALID_ARGUMENT => {
            let msg = get_last_error().unwrap_or_else(|| "Invalid argument".to_string());
            Err(FlashInferError::invalid_config(msg))
        }
        FlashInferStatus::FLASHINFER_OUT_OF_MEMORY => {
            let msg = get_last_error().unwrap_or_else(|| "Out of memory".to_string());
            Err(FlashInferError::OutOfMemory(msg))
        }
        FlashInferStatus::FLASHINFER_UNSUPPORTED => {
            let msg = get_last_error().unwrap_or_else(|| "Unsupported operation".to_string());
            Err(FlashInferError::unsupported(msg))
        }
        FlashInferStatus::FLASHINFER_INTERNAL_ERROR => {
            let msg = get_last_error().unwrap_or_else(|| "Internal error".to_string());
            Err(FlashInferError::Internal(msg))
        }
    }
}

/// Get the last error message from the FFI layer.
pub fn get_last_error() -> Option<String> {
    unsafe {
        let ptr = flashinfer_get_last_error();
        if ptr.is_null() {
            None
        } else {
            Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
        }
    }
}

/// Clear the last error message.
pub fn clear_last_error() {
    unsafe {
        flashinfer_clear_last_error();
    }
}

/// Get FlashInfer version string.
pub fn version() -> &'static str {
    unsafe {
        let ptr = flashinfer_version();
        if ptr.is_null() {
            "unknown"
        } else {
            CStr::from_ptr(ptr).to_str().unwrap_or("unknown")
        }
    }
}

/// Check if the current GPU supports FlashInfer operations.
///
/// Returns (supported, sm_version) where sm_version is e.g. 80 for SM80.
pub fn check_gpu_support() -> Result<(bool, i32)> {
    let mut supported: i32 = 0;
    let mut sm_version: i32 = 0;

    let status = unsafe { flashinfer_check_gpu_support(&mut supported, &mut sm_version) };

    check_status(status)?;
    Ok((supported != 0, sm_version))
}

/// Data type for attention computation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DType {
    Float16,
    BFloat16,
    Float32,
    Float8E4M3,
    Float8E5M2,
}

impl From<DType> for FlashInferDType {
    fn from(dtype: DType) -> Self {
        match dtype {
            DType::Float16 => FlashInferDType::FLASHINFER_DTYPE_FLOAT16,
            DType::BFloat16 => FlashInferDType::FLASHINFER_DTYPE_BFLOAT16,
            DType::Float32 => FlashInferDType::FLASHINFER_DTYPE_FLOAT32,
            DType::Float8E4M3 => FlashInferDType::FLASHINFER_DTYPE_FLOAT8_E4M3,
            DType::Float8E5M2 => FlashInferDType::FLASHINFER_DTYPE_FLOAT8_E5M2,
        }
    }
}

impl From<crate::DataType> for DType {
    fn from(dtype: crate::DataType) -> Self {
        match dtype {
            crate::DataType::Float16 => DType::Float16,
            crate::DataType::BFloat16 => DType::BFloat16,
            crate::DataType::Float32 => DType::Float32,
        }
    }
}

/// KV cache memory layout.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KVLayout {
    /// [num_pages, num_heads, page_size, head_dim]
    HND,
    /// [num_pages, page_size, num_heads, head_dim]
    NHD,
}

impl From<KVLayout> for FlashInferKVLayout {
    fn from(layout: KVLayout) -> Self {
        match layout {
            KVLayout::HND => FlashInferKVLayout::FLASHINFER_KV_LAYOUT_HND,
            KVLayout::NHD => FlashInferKVLayout::FLASHINFER_KV_LAYOUT_NHD,
        }
    }
}

/// Position encoding mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum PosEncoding {
    #[default]
    None,
    RoPELlama,
    ALiBi,
}

impl From<PosEncoding> for FlashInferPosEncoding {
    fn from(enc: PosEncoding) -> Self {
        match enc {
            PosEncoding::None => FlashInferPosEncoding::FLASHINFER_POS_ENCODING_NONE,
            PosEncoding::RoPELlama => FlashInferPosEncoding::FLASHINFER_POS_ENCODING_ROPE_LLAMA,
            PosEncoding::ALiBi => FlashInferPosEncoding::FLASHINFER_POS_ENCODING_ALIBI,
        }
    }
}

/// Get required workspace sizes for batch decode operation.
pub fn batch_decode_workspace_size(
    batch_size: i32,
    num_qo_heads: i32,
    num_kv_heads: i32,
    head_dim: i32,
    page_size: i32,
    max_seq_len: i32,
) -> Result<(usize, usize)> {
    let mut float_size: usize = 0;
    let mut int_size: usize = 0;

    let status = unsafe {
        flashinfer_batch_decode_workspace_size(
            &mut float_size,
            &mut int_size,
            batch_size,
            num_qo_heads,
            num_kv_heads,
            head_dim,
            page_size,
            max_seq_len,
        )
    };

    check_status(status)?;
    Ok((float_size, int_size))
}

/// Get required workspace sizes for batch prefill operation.
pub fn batch_prefill_workspace_size(
    batch_size: i32,
    total_tokens: i32,
    num_qo_heads: i32,
    num_kv_heads: i32,
    head_dim: i32,
    page_size: i32,
    max_seq_len: i32,
) -> Result<(usize, usize)> {
    let mut float_size: usize = 0;
    let mut int_size: usize = 0;

    let status = unsafe {
        flashinfer_batch_prefill_workspace_size(
            &mut float_size,
            &mut int_size,
            batch_size,
            total_tokens,
            num_qo_heads,
            num_kv_heads,
            head_dim,
            page_size,
            max_seq_len,
        )
    };

    check_status(status)?;
    Ok((float_size, int_size))
}

/// RAII wrapper for batch decode plan.
pub struct BatchDecodePlan {
    handle: FlashInferBatchDecodePlanHandle,
}

impl BatchDecodePlan {
    /// Create a new batch decode plan.
    ///
    /// # Arguments
    /// * `float_workspace` - GPU buffer for float workspace
    /// * `int_workspace` - GPU buffer for int workspace
    /// * `page_locked_workspace` - Page-locked host memory (optional, can be null)
    /// * `kv_indptr` - Cumulative page counts [batch_size + 1]
    /// * `batch_size` - Number of sequences
    /// * `num_qo_heads` - Number of query/output heads
    /// * `num_kv_heads` - Number of key/value heads
    /// * `head_dim` - Head dimension
    /// * `page_size` - Tokens per page
    /// * `dtype` - Data type
    /// * `pos_encoding` - Position encoding mode
    /// * `logits_soft_cap` - Soft cap for logits (0 to disable)
    /// * `enable_cuda_graph` - Whether this will run in a CUDA graph
    /// * `stream` - CUDA stream (raw pointer)
    #[allow(clippy::too_many_arguments)]
    pub unsafe fn new(
        float_workspace: *mut std::ffi::c_void,
        float_workspace_size: usize,
        int_workspace: *mut std::ffi::c_void,
        int_workspace_size: usize,
        page_locked_workspace: *mut std::ffi::c_void,
        page_locked_size: usize,
        kv_indptr: *const i32,
        batch_size: i32,
        num_qo_heads: i32,
        num_kv_heads: i32,
        head_dim: i32,
        page_size: i32,
        dtype: DType,
        pos_encoding: PosEncoding,
        logits_soft_cap: f32,
        enable_cuda_graph: bool,
        stream: *mut std::ffi::c_void,
    ) -> Result<Self> {
        let mut handle: FlashInferBatchDecodePlanHandle = ptr::null_mut();

        let status = flashinfer_batch_decode_plan(
            &mut handle,
            float_workspace,
            float_workspace_size,
            int_workspace,
            int_workspace_size,
            page_locked_workspace,
            page_locked_size,
            kv_indptr,
            batch_size,
            num_qo_heads,
            num_kv_heads,
            head_dim,
            page_size,
            dtype.into(),
            pos_encoding.into(),
            logits_soft_cap,
            enable_cuda_graph as i32,
            stream,
        );

        check_status(status)?;
        Ok(Self { handle })
    }

    /// Execute batch decode with this plan.
    #[allow(clippy::too_many_arguments)]
    pub unsafe fn run(
        &self,
        q: *const std::ffi::c_void,
        k_cache: *const std::ffi::c_void,
        v_cache: *const std::ffi::c_void,
        kv_indptr: *const i32,
        kv_indices: *const i32,
        kv_last_page_len: *const i32,
        output: *mut std::ffi::c_void,
        lse: *mut f32,
        kv_layout: KVLayout,
        stream: *mut std::ffi::c_void,
    ) -> Result<()> {
        let status = flashinfer_batch_decode_run(
            self.handle,
            q,
            k_cache,
            v_cache,
            kv_indptr,
            kv_indices,
            kv_last_page_len,
            output,
            lse,
            kv_layout.into(),
            stream,
        );

        check_status(status)
    }
}

impl Drop for BatchDecodePlan {
    fn drop(&mut self) {
        unsafe {
            flashinfer_batch_decode_plan_destroy(self.handle);
        }
    }
}

// BatchDecodePlan is Send but not Sync (single-threaded use)
unsafe impl Send for BatchDecodePlan {}

/// RAII wrapper for batch prefill plan.
pub struct BatchPrefillPlan {
    handle: FlashInferBatchPrefillPlanHandle,
}

impl BatchPrefillPlan {
    /// Create a new batch prefill plan.
    #[allow(clippy::too_many_arguments)]
    pub unsafe fn new(
        float_workspace: *mut std::ffi::c_void,
        float_workspace_size: usize,
        int_workspace: *mut std::ffi::c_void,
        int_workspace_size: usize,
        page_locked_workspace: *mut std::ffi::c_void,
        page_locked_size: usize,
        qo_indptr: *const i32,
        kv_indptr: *const i32,
        batch_size: i32,
        num_qo_heads: i32,
        num_kv_heads: i32,
        head_dim: i32,
        page_size: i32,
        dtype: DType,
        pos_encoding: PosEncoding,
        logits_soft_cap: f32,
        causal: bool,
        enable_cuda_graph: bool,
        stream: *mut std::ffi::c_void,
    ) -> Result<Self> {
        let mut handle: FlashInferBatchPrefillPlanHandle = ptr::null_mut();

        let status = flashinfer_batch_prefill_plan(
            &mut handle,
            float_workspace,
            float_workspace_size,
            int_workspace,
            int_workspace_size,
            page_locked_workspace,
            page_locked_size,
            qo_indptr,
            kv_indptr,
            batch_size,
            num_qo_heads,
            num_kv_heads,
            head_dim,
            page_size,
            dtype.into(),
            pos_encoding.into(),
            logits_soft_cap,
            causal as i32,
            enable_cuda_graph as i32,
            stream,
        );

        check_status(status)?;
        Ok(Self { handle })
    }

    /// Execute batch prefill with this plan.
    #[allow(clippy::too_many_arguments)]
    pub unsafe fn run(
        &self,
        q: *const std::ffi::c_void,
        k_cache: *const std::ffi::c_void,
        v_cache: *const std::ffi::c_void,
        kv_indptr: *const i32,
        kv_indices: *const i32,
        kv_last_page_len: *const i32,
        qo_indptr: *const i32,
        output: *mut std::ffi::c_void,
        lse: *mut f32,
        kv_layout: KVLayout,
        stream: *mut std::ffi::c_void,
    ) -> Result<()> {
        let status = flashinfer_batch_prefill_run(
            self.handle,
            q,
            k_cache,
            v_cache,
            kv_indptr,
            kv_indices,
            kv_last_page_len,
            qo_indptr,
            output,
            lse,
            kv_layout.into(),
            stream,
        );

        check_status(status)
    }
}

impl Drop for BatchPrefillPlan {
    fn drop(&mut self) {
        unsafe {
            flashinfer_batch_prefill_plan_destroy(self.handle);
        }
    }
}

unsafe impl Send for BatchPrefillPlan {}

/// Append new key-value pairs to paged KV cache.
#[allow(clippy::too_many_arguments)]
pub unsafe fn append_paged_kv_cache(
    k: *const std::ffi::c_void,
    v: *const std::ffi::c_void,
    k_cache: *mut std::ffi::c_void,
    v_cache: *mut std::ffi::c_void,
    kv_indptr: *const i32,
    kv_indices: *const i32,
    kv_last_page_len: *const i32,
    append_indptr: *const i32,
    batch_size: i32,
    num_kv_heads: i32,
    head_dim: i32,
    page_size: i32,
    dtype: DType,
    kv_layout: KVLayout,
    stream: *mut std::ffi::c_void,
) -> Result<()> {
    let status = flashinfer_append_paged_kv_cache(
        k,
        v,
        k_cache,
        v_cache,
        kv_indptr,
        kv_indices,
        kv_last_page_len,
        append_indptr,
        batch_size,
        num_kv_heads,
        head_dim,
        page_size,
        dtype.into(),
        kv_layout.into(),
        stream,
    );

    check_status(status)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version() {
        let v = version();
        assert!(!v.is_empty());
    }

    #[test]
    fn test_dtype_conversion() {
        assert_eq!(
            FlashInferDType::from(DType::Float16),
            FlashInferDType::FLASHINFER_DTYPE_FLOAT16
        );
        assert_eq!(
            FlashInferDType::from(DType::BFloat16),
            FlashInferDType::FLASHINFER_DTYPE_BFLOAT16
        );
    }

    #[test]
    fn test_layout_conversion() {
        assert_eq!(
            FlashInferKVLayout::from(KVLayout::HND),
            FlashInferKVLayout::FLASHINFER_KV_LAYOUT_HND
        );
        assert_eq!(
            FlashInferKVLayout::from(KVLayout::NHD),
            FlashInferKVLayout::FLASHINFER_KV_LAYOUT_NHD
        );
    }
}
